# Generated by Django 3.2.5 on 2022-06-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='puzzle_solution',
        ),
    ]
